### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by rcallaha** [LSDtopotools/LSDTopoTools_AnalysisDriver#1]
Hello,

I am having an issue compiling the code using the make function for the Analysis driver. I am receiving the following error.

In file included from ./../TNT/tnt.h:55:
./../TNT/tnt_sparse_matrix_csr.h:97:18: error: no matching constructor for
      initialization of 'Array1D<int>'
                rowptr_(M, r), colind_(nz, c), dim1_(M), dim2_(N) {}

I am mostly interested in the CRN Basinwide package, and see the same error when using the make command in that package as well. Any help would be greatly appreciated.

Thanks,
Russell Callahan
PhD Student
University of Wyoming

**Comment by simon-m-mudd** [comment]
Hi Russell, 
I'm unable to reproduce this error. Are you using the vagrant setup? I've just compiled using the vagrant distribution and also using a fresh clone on our Linux servers without any errors. 

The reasons I can think of for this happening are
i) You have a weird compiler (but the makefiles call for g++, so that seems unlikely).
ii) Something has happened to the line endings on your computer for that particular line in TNT (but again, why only that line?). 

If you use the vagrant distribution you should have the exact same operating environment as I do so it would be extremely strange for it not to compile under these conditions.
Simon

**Comment by rcallaha** [comment]
Simon,

Thanks for your help, I just got the make command to work, it was a problem with my directory structure, turns out I wasn’t in the vagrant directory, so I was trying to do these commands through OSX rather than Linux. Rookie mistake on my part, sorry for any inconvenience. Looking forward to being able to use the package now!

Cheers,
Russell

**Comment by simon-m-mudd** [comment]
Hi Russell, 
Glad to hear it is working. Please let me know if any of the documentation is unclear...all feedback is appreciated.
Simon
